---
default_platform: android
android:
  platformName: Android
  appium:options:
    url: http://localhost:4723/wd/hub
    platformVersion: '12'
    automationName: UiAutomator2
    deviceName: Pixel 3 API 32
    app: https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/Android-MyDemoAppRN.1.3.0.build-244.apk
ios:
  platformName: iOS
  appium:options:
    url: http://localhost:4723/wd/hub
    platformVersion: "14.0"
    deviceName: iPhone 11
    automationName: XCUITest
    app: "/Users/apeque01/Desktop/mobile_practice_1/mobile_session_1/MyRNDemoApp.app"
    autoDismissAlerts: true