---
default_platform: ios
android:
  url: http://localhost:4723/wd/hub
  platformName: Android
  platformVersion: '8.1'
  deviceName: Nexus
  appWaitActivity: com.address.book.MainActivity
  app: https://github.com/address-book/mobile_apps/blob/master/AddressBook.apk?raw=true
ios:
  platformName: iOS
  appium:options:
    platformVersion: "14.0"
    deviceName: iPhone 11
    automationName: XCUITest
    app: "/Users/apeque01/Desktop/mobile_practice_1/mobile_session_1/MyRNDemoApp.app"
    autoDismissAlerts: true